import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

/**
 * The custom XMP namespace originals are preserved in (SPEC §9.3).
 *
 * ExifTool will not write a tag it does not know, so the namespace has to be declared
 * in a config file handed to it at launch. It is generated rather than shipped as an
 * asset because it then cannot go missing from a build, and it is written where the
 * app already keeps state rather than beside the photos — it is not folder state.
 */

export const GEOTAGGER_NAMESPACE = 'http://ns.geotagger.local/1.0/';
export const GEOTAGGER_GROUP = 'XMP-geotagger';
export const CONFIG_FILENAME = 'geotagger.exiftool.config';

/** The tags of SPEC §9.3, in the order they are declared to ExifTool. */
export const GEOTAGGER_TAGS = [
  'OriginalGPSPresent',
  'OriginalGPSLatitude',
  'OriginalGPSLongitude',
  'OriginalDateTimeOriginal',
  'OriginalOffsetTimeOriginal',
  'PositionSource',
  'PositionUncertaintyMeters',
  'TimeShiftSeconds',
  'ModifiedAt',
  'AppVersion',
] as const;

export type GeotaggerTag = (typeof GEOTAGGER_TAGS)[number];

function configSource(): string {
  const tagLines = GEOTAGGER_TAGS.map((tag) => `        ${tag} => { },`).join('\n');
  return `# Generated by GeoTagger. Declares the XMP namespace that SPEC §9.3 preserves
# each file's pre-GeoTagger values in, so that a revert works from the file alone.
%Image::ExifTool::UserDefined::geotagger = (
    GROUPS    => { 0 => 'XMP', 1 => '${GEOTAGGER_GROUP}', 2 => 'Image' },
    NAMESPACE => { 'geotagger' => '${GEOTAGGER_NAMESPACE}' },
    WRITABLE  => 'string',
${tagLines}
);

%Image::ExifTool::UserDefined = (
    'Image::ExifTool::XMP::Main' => {
        geotagger => {
            SubDirectory => {
                TagTable => 'Image::ExifTool::UserDefined::geotagger',
            },
        },
    },
);

1;  # end
`;
}

/**
 * Writes the config and returns its path, or null when it cannot be written.
 *
 * A failure is not fatal: the same snapshot goes into the edit store either way
 * (SPEC §9.3), so what is lost is the ability to revert a file that has been separated
 * from its `.geotagger` directory — worth a warning, not worth refusing to run.
 */
export function ensureExiftoolConfig(stateDir: string): string | null {
  for (const dir of [stateDir, path.join(os.tmpdir(), 'geotagger')]) {
    try {
      fs.mkdirSync(dir, { recursive: true });
      const target = path.join(dir, CONFIG_FILENAME);
      const source = configSource();
      // Rewritten only when it differs, so a read-only but already-correct config
      // directory keeps working.
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== source) {
        fs.writeFileSync(target, source);
      }
      return target;
    } catch {
      continue;
    }
  }
  return null;
}
